version: '3'
services:
  composer:
    image: composer
    volumes:
      - ./src:/app
    command: composer install
  php-fpm:
    image: php:7.1-fpm
    volumes:
      - ./src:/app
  nginx:
    image: nginx
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./src:/app
    ports:
      - 18080:80
