version: '3'
services:
  composer:
    image: composer
    volumes:
      - ./src:/app
    command: install --ignore-platform-reqs
  php-fpm:
    image: php:7.1-fpm
    volumes:
      - ./src:/app
  nginx:
    image: nginx
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./src:/app
    ports:
      - 3000:80
